title: Status Page
baseURL: ''
languageCode: en
params:
  copyrightHolder: Contz
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: ''
  description_header: ''
  eventsPerPage: 10
  logo: 'https://contz.com.br/contz/images/contz_preto.png'
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: ''
      link: 'https://contz.com.br'
      name: Website
    - link: 'https://sandbox.contz.com.br'
      name: Sandbox
    - link: 'https://dashboard.contz.com.br'
      name: Dashboard
  timezoneString: ' UTC'
